/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BotsInfoSchema : Schema for successful response from bots.info method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotsInfoSchema {
    #[serde(rename = "bot")]
    pub bot: crate::models::BotsInfoSchemaBot,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl BotsInfoSchema {
    /// Schema for successful response from bots.info method
    pub fn new(bot: crate::models::BotsInfoSchemaBot, ok: crate::models::DefsOkTrue) -> BotsInfoSchema {
        BotsInfoSchema {
            bot,
            ok,
        }
    }
}


