/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelsSetTopicSchema : Schema for successful response from channels.setTopic method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelsSetTopicSchema {
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
    #[serde(rename = "topic")]
    pub topic: String,
}

impl ChannelsSetTopicSchema {
    /// Schema for successful response from channels.setTopic method
    pub fn new(ok: crate::models::DefsOkTrue, topic: String) -> ChannelsSetTopicSchema {
        ChannelsSetTopicSchema {
            ok,
            topic,
        }
    }
}


