/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatPostMessageErrorSchema : Schema for error response chat.postMessage method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatPostMessageErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl ChatPostMessageErrorSchema {
    /// Schema for error response chat.postMessage method
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> ChatPostMessageErrorSchema {
        ChatPostMessageErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "not_in_channel")]
    NotInChannel,
    #[serde(rename = "is_archived")]
    IsArchived,
    #[serde(rename = "msg_too_long")]
    MsgTooLong,
    #[serde(rename = "no_text")]
    NoText,
    #[serde(rename = "too_many_attachments")]
    TooManyAttachments,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "not_authed")]
    NotAuthed,
    #[serde(rename = "invalid_auth")]
    InvalidAuth,
    #[serde(rename = "account_inactive")]
    AccountInactive,
    #[serde(rename = "invalid_arg_name")]
    InvalidArgName,
    #[serde(rename = "invalid_array_arg")]
    InvalidArrayArg,
    #[serde(rename = "invalid_charset")]
    InvalidCharset,
    #[serde(rename = "invalid_form_data")]
    InvalidFormData,
    #[serde(rename = "invalid_post_type")]
    InvalidPostType,
    #[serde(rename = "missing_post_type")]
    MissingPostType,
}

