/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatScheduledMessagesListSchemaResponseMetadata {
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
}

impl ChatScheduledMessagesListSchemaResponseMetadata {
    pub fn new(next_cursor: String) -> ChatScheduledMessagesListSchemaResponseMetadata {
        ChatScheduledMessagesListSchemaResponseMetadata {
            next_cursor,
        }
    }
}


