/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GroupsHistoryErrorSchema : Schema for error response groups.history method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupsHistoryErrorSchema {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkFalse,
}

impl GroupsHistoryErrorSchema {
    /// Schema for error response groups.history method
    pub fn new(error: Error, ok: crate::models::DefsOkFalse) -> GroupsHistoryErrorSchema {
        GroupsHistoryErrorSchema {
            error,
            ok,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "channel_not_found")]
    ChannelNotFound,
    #[serde(rename = "invalid_ts_latest")]
    InvalidTsLatest,
    #[serde(rename = "invalid_ts_oldest")]
    InvalidTsOldest,
    #[serde(rename = "not_authed")]
    NotAuthed,
    #[serde(rename = "invalid_auth")]
    InvalidAuth,
    #[serde(rename = "account_inactive")]
    AccountInactive,
    #[serde(rename = "token_revoked")]
    TokenRevoked,
    #[serde(rename = "no_permission")]
    NoPermission,
    #[serde(rename = "org_login_required")]
    OrgLoginRequired,
    #[serde(rename = "ekm_access_denied")]
    EkmAccessDenied,
    #[serde(rename = "missing_scope")]
    MissingScope,
    #[serde(rename = "invalid_arguments")]
    InvalidArguments,
    #[serde(rename = "invalid_arg_name")]
    InvalidArgName,
    #[serde(rename = "invalid_charset")]
    InvalidCharset,
    #[serde(rename = "invalid_form_data")]
    InvalidFormData,
    #[serde(rename = "invalid_post_type")]
    InvalidPostType,
    #[serde(rename = "missing_post_type")]
    MissingPostType,
    #[serde(rename = "team_added_to_org")]
    TeamAddedToOrg,
    #[serde(rename = "request_timeout")]
    RequestTimeout,
    #[serde(rename = "fatal_error")]
    FatalError,
}

