/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GroupsRepliesSchema : Schema for successful response from groups.replies method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupsRepliesSchema {
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "messages")]
    pub messages: Vec<crate::models::ObjsMessage>,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl GroupsRepliesSchema {
    /// Schema for successful response from groups.replies method
    pub fn new(messages: Vec<crate::models::ObjsMessage>, ok: crate::models::DefsOkTrue) -> GroupsRepliesSchema {
        GroupsRepliesSchema {
            has_more: None,
            messages,
            ok,
        }
    }
}


