/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjsUserProfile {
    #[serde(rename = "always_active", skip_serializing_if = "Option::is_none")]
    pub always_active: Option<bool>,
    #[serde(rename = "api_app_id", skip_serializing_if = "Option::is_none")]
    pub api_app_id: Option<String>,
    #[serde(rename = "avatar_hash")]
    pub avatar_hash: String,
    #[serde(rename = "bot_id", skip_serializing_if = "Option::is_none")]
    pub bot_id: Option<String>,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "display_name_normalized")]
    pub display_name_normalized: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "guest_expiration_ts", skip_serializing_if = "Option::is_none")]
    pub guest_expiration_ts: Option<i32>,
    #[serde(rename = "guest_invited_by", skip_serializing_if = "Option::is_none")]
    pub guest_invited_by: Option<String>,
    #[serde(rename = "image_1024", skip_serializing_if = "Option::is_none")]
    pub image_1024: Option<String>,
    #[serde(rename = "image_192", skip_serializing_if = "Option::is_none")]
    pub image_192: Option<String>,
    #[serde(rename = "image_24", skip_serializing_if = "Option::is_none")]
    pub image_24: Option<String>,
    #[serde(rename = "image_32", skip_serializing_if = "Option::is_none")]
    pub image_32: Option<String>,
    #[serde(rename = "image_48", skip_serializing_if = "Option::is_none")]
    pub image_48: Option<String>,
    #[serde(rename = "image_512", skip_serializing_if = "Option::is_none")]
    pub image_512: Option<String>,
    #[serde(rename = "image_72", skip_serializing_if = "Option::is_none")]
    pub image_72: Option<String>,
    #[serde(rename = "image_original", skip_serializing_if = "Option::is_none")]
    pub image_original: Option<String>,
    #[serde(rename = "is_custom_image", skip_serializing_if = "Option::is_none")]
    pub is_custom_image: Option<bool>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "real_name")]
    pub real_name: String,
    #[serde(rename = "real_name_normalized")]
    pub real_name_normalized: String,
    #[serde(rename = "skype", skip_serializing_if = "Option::is_none")]
    pub skype: Option<String>,
    #[serde(rename = "status_emoji", skip_serializing_if = "Option::is_none")]
    pub status_emoji: Option<String>,
    #[serde(rename = "status_expiration", skip_serializing_if = "Option::is_none")]
    pub status_expiration: Option<i32>,
    #[serde(rename = "status_text", skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
    #[serde(rename = "status_text_canonical", skip_serializing_if = "Option::is_none")]
    pub status_text_canonical: Option<String>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<String>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl ObjsUserProfile {
    pub fn new(avatar_hash: String, display_name: String, display_name_normalized: String, real_name: String, real_name_normalized: String) -> ObjsUserProfile {
        ObjsUserProfile {
            always_active: None,
            api_app_id: None,
            avatar_hash,
            bot_id: None,
            display_name,
            display_name_normalized,
            email: None,
            first_name: None,
            guest_expiration_ts: None,
            guest_invited_by: None,
            image_1024: None,
            image_192: None,
            image_24: None,
            image_32: None,
            image_48: None,
            image_512: None,
            image_72: None,
            image_original: None,
            is_custom_image: None,
            last_name: None,
            phone: None,
            real_name,
            real_name_normalized,
            skype: None,
            status_emoji: None,
            status_expiration: None,
            status_text: None,
            status_text_canonical: None,
            team: None,
            teams: None,
            title: None,
        }
    }
}


