/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjsConversationImShares {
    #[serde(rename = "date_create")]
    pub date_create: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "team")]
    pub team: crate::models::ObjsTeam,
}

impl ObjsConversationImShares {
    pub fn new(date_create: i32, id: String, is_active: bool, name: String, team: crate::models::ObjsTeam) -> ObjsConversationImShares {
        ObjsConversationImShares {
            date_create,
            id,
            is_active,
            name,
            team,
        }
    }
}


