/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TeamBillableInfoSchema : Schema for successful response from team.billableInfo method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamBillableInfoSchema {
    #[serde(rename = "billable_info")]
    pub billable_info: serde_json::Value,
    #[serde(rename = "ok")]
    pub ok: crate::models::DefsOkTrue,
}

impl TeamBillableInfoSchema {
    /// Schema for successful response from team.billableInfo method
    pub fn new(billable_info: serde_json::Value, ok: crate::models::DefsOkTrue) -> TeamBillableInfoSchema {
        TeamBillableInfoSchema {
            billable_info,
            ok,
        }
    }
}


